### ISSUE TITLE
customize columns in 'routes' overview

### ISSUE THREAD

**Issue by job** [ecix/birdseye#10]
Right now it displays:

```Network	Gateway	Interface	Metric```

I'd like:

```Network AS_PATH  Gateway```

**Comment by hellerve** [comment]
We already thought about that. The birdwatcher already has a setting to filter out certain fields, the birdseye still needs configuration there.

**Comment by hellerve** [comment]
Heads up: this is now fixed. The configuration for this is as follows:

Within your birdseye.conf, you have a new section called `routes_columns` filled with `<property> = <heading>` pairs. Example values for how this could look:
```
[routes_columns]
metric = Metric     # regular property
bgp.as_path = AS Path # nested property
```
If the values are lists (as in the `AS Path`), they will be joined with a space character.

I hope this suits your needs.

Cheers

**Comment by job** [comment]
Seems routes are no longer displayed? https://lg.coloclue.net/birdseye/app/routeservers/0/protocols/peer_AS1200_4672GR/routes

I did git pull, `make client`, and added your suggestion to the config file and restarted the uwsgi process (in this order), anything else I should do?

**Comment by hellerve** [comment]
They do display for me, but the requests to the birdwatcher take 24 seconds when not cached (or, even worse, I get a 502). I thus assume this is a problem with the birdwatcher. Could you tell me which version you are running, or rather when you last pulled (maybe you even have a commit hash)?
![bildschirmfoto 2017-03-01 um 10 49 02](https://cloud.githubusercontent.com/assets/7725188/23454503/bcc0cd2a-fe6c-11e6-964c-7d99183c21e2.png)

**Comment by job** [comment]
I see, I am impatient :)

I'm running 9c4a47fd11b8fc2d6e0c322b55d68896f8beb5a3

**Comment by job** [comment]
How can I suppress columns? Metric & interface are not interesting to me :)

**Comment by hellerve** [comment]
If you don't write them in `routes_colums`, they will not be displayed. Keep in mind that config changes require a server restart.
