### ISSUE TITLE
Display communities in canonical way

### ISSUE THREAD

**Issue by job** [ecix/birdseye#9]
When you click a route, the communities are displayed like this:

```
Communities:	(6830, 11492) (6830, 13000) (6830, 13272) (6830, 23001) (6830, 34904) (8283, 1)
Large Communities:	(8283, 0, 1) (8283, 7, 6)
```

It should display like this:

```
Communities:	6830:11492 6830:13000 6830:13272 6830:23001 6830:34904 8283:1
Large Communities:	8283:0:1 8283:7:6
```

**Comment by hellerve** [comment]
Thanks again.

**Comment by job** [comment]
White space is missing:

```Large Communities:	8283:0:18283:7:4```

**Comment by hellerve** [comment]
Should be resolved.

**Comment by job** [comment]
This breaks displaying the reasons why a route was rejected: http://instituut.net/~job/screenshots/9cd8cf5442365f5f.png

**Comment by hellerve** [comment]
Wut. Okay. Looking into it.

**Comment by hellerve** [comment]
Ah, that was actually an unrelated regression introduced by a commit from this morning (in commit 7955d5a).
